language: node_js
node_js:
- "6.9"

script:
  - npm run test
  - npm run build

before_deploy:
  - zip -r web-app-latest build/ appspec.yml scripts/stop-server.sh
  - mkdir -p web-app
  - mv web-app-latest.zip web-app/

deploy:
  - provider: s3
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: web-app
    skip_cleanup: true
    on:
      branch: develop
    bucket: amscores-deploy-dev
  - provider: codedeploy
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: "amscores-deploy-dev"
    key: web-app-latest.zip
    bundle_type: zip
    application: AmScoresWebApp
    deployment_group: Development
    on:
      branch: develop
    wait-until-deployed: true
