language: node_js
node_js:
- "6.9"

script:
  - npm run-script testAll
  - npm run build

before_deploy:
  - zip -r web-app-latest build/ appspec.yml scripts/stop-server.sh
  - mkdir -p web-app
  - mv web-app-latest.zip web-app/

after-success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  - provider: s3
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    local_dir: web-app
    skip_cleanup: true
    upload-dir: dev
    on:
      branch: develop
    bucket: amscores-deploy
  - provider: codedeploy
    access_key_id: $AMSCORES_AWS_KEY_ID
    secret_access_key: $AMSCORES_AWS_KEY_SECRET
    region: us-east-1
    bucket: "amscores-deploy"
    key: dev/web-app-latest.zip
    bundle_type: zip
    application: AmScoresWebApp
    deployment_group: Development
    on:
      branch: develop
    wait-until-deployed: true